import image from "@/assets/class.png";

export const classData = {
  "9": [
    {
      subject: "English Language Arts",
      count: "125 Total Podcast Classes",
      description: "An extensive study of the English language and literature.",
      chapters: "13 Chapters",
      image: image.src,
    },
    {
      subject: "Science",
      count: "125 Total Podcast Classes",
      description: "An in-depth exploration of various scientific principles.",
      chapters: "13 Chapters",
      image: image.src,
    },
    {
      subject: "Mathematics",
      count: "125 Total Podcast Classes",
      description: "Covering algebra, geometry, and more advanced topics.",
      chapters: "13 Chapters",
      image: image.src,
    },
    {
      subject: "Social Studies",
      count: "125 Total Podcast Classes",
      description: "Understanding human societies and global history.",
      chapters: "13 Chapters",
      image: image.src,
    },
    {
      subject: "Art",
      count: "125 Total Podcast Classes",
      description: "Exploring different art techniques and history.",
      chapters: "13 Chapters",
      image: image.src,
    },
    {
      subject: "Computer Science",
      count: "125 Total Podcast Classes",
      description: "Programming basics and computer science fundamentals.",
      chapters: "13 Chapters",
      image: image.src,
    },
  ],
  "10": [
    {
      subject: "Advanced English",
      count: "130 Total Podcast Classes",
      description: "Advanced study of English literature and composition.",
      chapters: "13 Chapters",
      image: image.src,
    },
    {
      subject: "Physics",
      count: "120 Total Podcast Classes",
      description: "Exploring the fundamentals of physics and the universe.",
      chapters: "13 Chapters",
      image: image.src,
    },
    {
      subject: "Algebra",
      count: "135 Total Podcast Classes",
      description: "Mastering algebraic equations and functions.",
      chapters: "13 Chapters",
      image: image.src,
    },
    {
      subject: "World History",
      count: "115 Total Podcast Classes",
      description: "Studying key historical events around the world.",
      chapters: "13 Chapters",
      image: image.src,
    },
    {
      subject: "Visual Arts",
      count: "100 Total Podcast Classes",
      description: "Understanding the theory and practice of visual arts.",
      chapters: "13 Chapters",
      image: image.src,
    },
    {
      subject: "Programming Basics",
      count: "110 Total Podcast Classes",
      description: "Introduction to programming concepts and languages.",
      chapters: "13 Chapters",
      image: image.src,
    },
  ],
  "11": [
    {
      subject: "Literature & Composition",
      count: "140 Total Podcast Classes",
      description: "A deep dive into literary analysis and composition.",
      chapters: "13 Chapters",
      image: image.src,
    },
    {
      subject: "Chemistry",
      count: "145 Total Podcast Classes",
      description: "Understanding the principles of chemistry and reactions.",
      chapters: "13 Chapters",
      image: image.src,
    },
    {
      subject: "Geometry & Trigonometry",
      count: "150 Total Podcast Classes",
      description: "Mastering geometry and trigonometric concepts.",
      chapters: "13 Chapters",
      image: image.src,
    },
    {
      subject: "Economics",
      count: "120 Total Podcast Classes",
      description: "Exploring the fundamentals of economics and markets.",
      chapters: "13 Chapters",
      image: image.src,
    },
    {
      subject: "Digital Media",
      count: "105 Total Podcast Classes",
      description:
        "Learning how digital media influences society and technology.",
      chapters: "13 Chapters",
      image: image.src,
    },
    {
      subject: "Web Development",
      count: "130 Total Podcast Classes",
      description: "Creating websites and understanding web technologies.",
      chapters: "13 Chapters",
      image: image.src,
    },
  ],
  "12": [
    {
      subject: "Advanced Composition",
      count: "150 Total Podcast Classes",
      description:
        "Mastering advanced composition skills and writing techniques.",
      chapters: "13 Chapters",
      image: image.src,
    },
    {
      subject: "Biology",
      count: "155 Total Podcast Classes",
      description: "Exploring cellular biology, genetics, and ecosystems.",
      chapters: "13 Chapters",
      image: image.src,
    },
    {
      subject: "Calculus",
      count: "160 Total Podcast Classes",
      description: "An in-depth study of calculus concepts and techniques.",
      chapters: "13 Chapters",
      image: image.src,
    },
    {
      subject: "Political Science",
      count: "130 Total Podcast Classes",
      description: "Understanding political systems and theories.",
      chapters: "13 Chapters",
      image: image.src,
    },
    {
      subject: "Fine Arts",
      count: "110 Total Podcast Classes",
      description: "Exploring various fine art techniques and history.",
      chapters: "13 Chapters",
      image: image.src,
    },
    {
      subject: "Mobile App Development",
      count: "140 Total Podcast Classes",
      description: "Learning how to design and develop mobile applications.",
      chapters: "13 Chapters",
      image: image.src,
    },
  ],
};
