import type { Metadata } from 'next';
import './globals.css';
import { Poppins, Montserrat } from 'next/font/google';
import MyContextProvider from '@/lib/MyContextProvider';
import ReduxStoreProvider from '@/redux/ReduxStoreProvider';
import { Toaster } from 'sonner';

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700', '800', '900'],
  variable: '--font-poppins',
});

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700', '800', '900'],
  variable: '--font-montserrat',
});

export const metadata: Metadata = {
  title: 'Video Edu Platform',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${poppins.variable} ${montserrat.variable}`}
    >
      <body>
        <MyContextProvider>
          <ReduxStoreProvider>
            <Toaster richColors position="top-center" />
            {children}
          </ReduxStoreProvider>
        </MyContextProvider>
      </body>
    </html>
  );
}
