import type { Metadata } from "next";
import "./globals.css";
import { Poppins, Montserrat } from "next/font/google";
import MyContextProvider from "@/lib/MyContextProvider";
import ReduxStoreProvider from "@/redux/ReduxStoreProvider";
import { Toaster } from "sonner";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
});

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-montserrat",
});

export const metadata: Metadata = {
  title: "Brain Drawer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      suppressHydrationWarning={true}
      lang="en"
      data-theme="light"
      className={`${poppins.variable} ${montserrat.variable}`}
    >
      <body
        cz-shortcut-listen="true"
        data-new-gr-c-s-check-loaded="14.1238.0"
        data-gr-ext-installed=""
      >
        <MyContextProvider>
          <ReduxStoreProvider>
            <Toaster richColors />
            {children}
          </ReduxStoreProvider>
        </MyContextProvider>
      </body>
    </html>
  );
}
